version: '3'

services:

# SERVER
  server:
    build:
      context: .
      dockerfile: ./docker/dev/server/Dockerfile
    environment:
      GO111MODULE: 'on'
    links:
      - database
    ports:
      - 8080:3000

# CLIENT
  client:
    build:
      context: .
      dockerfile: ./docker/dev/client/Dockerfile
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    links:
      - server
    ports:
      - 8081:8080

# DEVELOPMENT UTILITIES
  database:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: "aggregatier"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - 8089:80