version: '3'

services:
  web:
    build:
      dockerfile: ./docker/dev/Dockerfile
    environment:
      GO111MODULE: 'on'
    links:
      - database

  database:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - 8081:80