apiVersion: v1
kind: Service
metadata:
  labels:
    app: aggregatier-api
  name: aggregatier-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: aggregatier-api
