apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregatier-client
  template:
    metadata:
      labels:
        app: aggregatier-client
    spec:
      containers:
        - image: wordpress
          name: aggregatier-client
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql:3306
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: password
          ports:
            - containerPort: 80
              name: aggregatier-client
